### ISSUE TITLE
ImportError: No module named six

### ISSUE THREAD

**Issue by chrishuan9** [kakulukia/django-secrets#2]
After installing django_secrets into a new virtual environment I got the following error after running manage.py:

```bash
(venv) chris@n:~/Django101$ pip install django-secrets
Collecting django-secrets
  Downloading https://files.pythonhosted.org/packages/dd/2e/7c2d2725aa77b5058256b23484d35b2c656bc7eb1dc70b78b32a031728f5/django_secrets-1.0.0-py2.py3-none-any.whl
Collecting future (from django-secrets)
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 932kB/s 
Requirement already satisfied: Django>=1.11 in ./venv/lib/python3.5/site-packages (from django-secrets)
Requirement already satisfied: pytz in ./venv/lib/python3.5/site-packages (from Django>=1.11->django-secrets)
Installing collected packages: future, django-secrets
  Running setup.py install for future ... done
Successfully installed django-secrets-1.0.0 future-0.16.0
(venv) chris@n:~/Django101$ python manage.py 
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from django_secrets.startup import check
  File "/Users/chris/Developer/PythonProjects/Django101/venv/lib/python3.5/site-packages/django_secrets/startup.py", line 4, in <module>
    from six.moves import input
ImportError: No module named 'six'
```

The error message is pretty clear. After I installed the module six ```pip install six``` the error went away. I suggest you should add six to the required packages.

**Comment by kakulukia** [comment]
Thx for reporting. That will be fixed soon.

**Comment by kakulukia** [comment]
Release pending because of https://github.com/pypa/pipenv/issues/2120
Will publish a new version as soon as Travis works again. :(

**Comment by kakulukia** [comment]
Okay, pipenv is still broken but i released a new version anyway, please retest and close he issue if its fixed for you now, @cvarta .

**Comment by chrishuan9** [comment]
@kakulukia , will test as soon as I am back home from my business trip , don’t have access to my dev machine atm.

**Comment by kakulukia** [comment]
What about now? :P

**Comment by chrishuan9** [comment]
@kakulukia , works like a charm, thanks for fixing it.
You can close this issue now.

LOG:
`(venv) chris@natsumi:$ pip install django-secrets
Collecting django-secrets
  Downloading https://files.pythonhosted.org/packages/aa/6d/78dbbc61119bda41ec432701b5aa89a12669c68598e953b89d3543efe64d/django_secrets-1.0.2-py2.py3-none-any.whl
https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting future (from django-secrets)
  Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Requirement already satisfied: Django>=1.5 in ./venv/lib/python3.6/site-packages (from django-secrets)
Requirement already satisfied: pytz in ./venv/lib/python3.6/site-packages (from Django>=1.5->django-secrets)
Installing collected packages: six, future, django-secrets
  Running setup.py install for future ... done
Successfully installed django-secrets-1.0.2 future-0.16.0 six-1.11.0
`

**Comment by Ravishrks** [comment]
I have fixed it, It happened as django dropped some third party module depedencies.
I have ready made solution for you. You don't need to fix django-hotsts yourself, just install it using pip from my github repo.

For detailed instructions visit below link.

https://dblogstream.com/article/detail/How-to-use-django-hosts-for-Django-3-and-above/

**Comment by kakulukia** [comment]
@Ravishrks i dont get what that has todo with the above issue with `six`?
